### ISSUE TITLE
Built Error with Remote Rendering in Unity 2022.2.0f1 [Remote rendering problem]

### ISSUE THREAD

**Issue by whatthemehek** [Azure/azure-remote-rendering#104]
When attempting to build a project with Azure Remote Rendering installed in Unity 2022.2.0f1, I get this error:

`Cannot include plugin 'Packages/com.microsoft.azure.remote-rendering/Plugins/WSA/ARM64/Microsoft.Holographic.HybridRemoting.lib' (Key: microsoft.holographic.hybridremoting.lib;None) since plugin with the same name and architecture was already added ('Packages/com.microsoft.azure.remote-rendering/Plugins/x86_64/Microsoft.Holographic.HybridRemoting.lib (Architecture: None)').`

Is there any way to combat this in this Unity version?

**Comment by jankrassnigg** [comment]
ARR currently doesn't support Unity 2022, see the [system requirements](https://learn.microsoft.com/en-us/azure/remote-rendering/overview/system-requirements#unity).

**Comment by jloehr** [comment]
Hi @whatthemehek, thanks for bringing this issue to our attention.

The issue seems that with Unity 2022 the importer for `.lib` files have changed from the default to the plugin importer. The new importer falls back to the default settings, which is "include in any platform".

We have a fix for it in-flight for the next release, which is scheduled for end of this week or early next week.
In the mean time, you can apply the fix yourself:
1. Embed the Azure Remote Rendering package in your project following this Unity guide: [Copying a Unity package from the cache](https://docs.unity3d.com/Manual/upm-embed.html#embed-cached)
2. Adjust the import settings of all `Microsoft.Holographic.HybridRemoting.lib` files to the import setting of the respective  `Microsoft.Holographic.HybridRemoting.dll` in the same folder. You find the `.lib` files in the following folders:
    1. `Plugins/WSA/ARM/`
    2. `Plugins/WSA/ARM64/`
    3. `Plugins/WSA/x64/`
    4. `Plugins/WSA/x86/`
    5. `Plugins/x86_64/`

**Comment by whatthemehek** [comment]
How do I adjust the import settings?

**Comment by jloehr** [comment]
Hi @whatthemehek, [release 1.2.2](https://github.com/Azure/azure-remote-rendering/releases/tag/1.2.2) is now public and contains the fix for this issue.

**Comment by whatthemehek** [comment]
Getting another weird error with Unity 2022.2.0f1- set up as normal and everything, using release 1.2.2, and in my browser, everything seems to be loading fine, no errors, but I can't see the loaded test model. Load Test Model is running with no errors, but no matter where I move my camera or whether it's reset, when it logs the model at 100% loaded, I see nothing. I've run it several times but no dice. Could this be an issue with clear flags? I noticed that setting isn't visible in Unity 2022.2.x, so I just set the background to solid color and the suggested color value.

**Comment by jloehr** [comment]
Hey, this sounds like a different unrelated issue. Could you be so kind and open a new issue, so we can properly track it?

When opening the new issue, also please include some more information, like which rendering pipeline are you using, which platform you are targeting and using in the Editor, as well as if this issue exists in the Unity Editor, build app or both. 

Also in the meantime, you can check our **Project Validator** for any issues or missing configurations. You can open the **Project Validator** window by choosing the the **Validate Project** entry from the **Remote Rendering** menu in the Unity editor toolbar.
