### ISSUE TITLE
[Question] Upgrading ARR Tutorials from MRTK2 to MRTK3

### ISSUE THREAD

**Issue by jtruo** [Azure/azure-remote-rendering#111]
Are there plans to update tutorials/sample projects such as:

https://learn.microsoft.com/en-us/azure/remote-rendering/tutorials/unity/manipulate-models/manipulate-models 

from MRTK2 to MRTK3? 

I've been porting some of the features myself, but I'm still needing to familiarize myself with the framework along the way, and I'm relatively inexperienced. The provided base code with MRTK2 has been helpful for the migration. With the recent news of MRTK3 being put into General Availability, I'm curious as to whether this is on the timeline.

**Comment by FlorianBorn71** [comment]
Hi,
MRTK3 migration of the samples (Showcase, tutorials) is definitely on our roadmap, but as of today, I cannot provide any specific timeline.
Due to the complexity of the Showcase app and the fundamental differences in MRTK3, it's not a simple 'port'. Once done, we hope that we'll be able to provide best practices for ARR/MRTK3, where the remote object interaction model is one of the key points.

Florian

**Comment by jtruo** [comment]
Thanks for the information, I was able to get some basic features that I needed on MRTK3 working with ARR, but I look forward for the official changes and best practices. It is good to hear that it's in the roadmap
