### ISSUE TITLE
[Remote rendering problem] No hit results from RayCastQueryResult.Hits is inconsistent between platforms (Quest and Windows)

### ISSUE THREAD

**Issue by WikkidEdd** [Azure/azure-remote-rendering#116]
SDK Version 1.2.6

We've recently updated the RemoteFocusProviderNoCollider to properly support the teleport pointer. This worked fine in Editor, but didn't return any hits when running on Quest. After some debugging, we tracked it down to some extra processing hits we added. 

The cause was that RayCastQueryResult.Hits returns null for no hits on Quest and an empty array on Windows. The comment on the property implies that it should be a at least and empty array and not null.

"A (potentially empty) array of <see cref="RayCastHit">intersections</see> that the raycast encountered."

It would great if this could be made consistent between platforms.

(Apologies if it's already been fixed in a newer version of the SDK, upgrading to the latest is on our backlog)

**Comment by jloehr** [comment]
Hi @WikkidEdd,

Yes, this has already been fixed with version [1.2.12](https://github.com/Azure/azure-remote-rendering/releases/tag/1.2.12). 

Starting with that versions all Unity APIs should return an empty Array/List instead of `null`. The only two exceptions are `RenderingSessionPropertiesArrayResult.SessionProperties` and `ConversionPropertiesArrayResult.Conversions`, which may still be returning `null`.

I highly recommend updating to version 1.2.12 or newer, and use the new preallocation APIs for retrieving the results. They greatly reduce the pressure on the GC compared to the regular APIs.

**Comment by WikkidEdd** [comment]
Ok, great. Will do!
