### ISSUE TITLE
Failed to load RemoteRenderingClient.dll

### ISSUE THREAD

**Issue by laoyigrace** [Azure/azure-remote-rendering#21]
**Describe the problem**
pc os: windows server 2016

Plugins: Failed to load 'C:/work/azure-remote-rendering/Unity/Quickstart/Library/PackageCache/com.microsoft.azure.remote-rendering@0.1.76/Plugins/x86_64/RemoteRenderingClient.dll' with error '找不到指定的程序。

can i help me? thanks.

![image](https://user-images.githubusercontent.com/10418154/104310298-72459d00-550e-11eb-9aad-158d43f1af67.png)

**Comment by jumeder** [comment]
Hi @laoyigrace, thanks for your inquiry and apologies for your inconvenience!

From what I can tell, Unity cannot load our binaries and/or respective dependencies. Can you follow the following steps:

1. Make sure the files listed in the error messages actually exist.
2. Please read and follow the steps listed on this page: https://docs.microsoft.com/en-us/azure/remote-rendering/overview/system-requirements. In particular, make sure you have all required software listed under "Software" installed.

Also please be aware that we require Windows 10 version 1903 or higher. Since you list Windows Server 2016 there might be incompatibilities.

**Comment by laoyigrace** [comment]
> Hi @laoyigrace, thanks for your inquiry and apologies for your inconvenience!
> 
> From what I can tell, Unity cannot load our binaries and/or respective dependencies. Can you follow the following steps:
> 
> 1. Make sure the files listed in the error messages actually exist.
> 2. Please read and follow the steps listed on this page: https://docs.microsoft.com/en-us/azure/remote-rendering/overview/system-requirements. In particular, make sure you have all required software listed under "Software" installed.
> 
> Also please be aware that we require Windows 10 version 1903 or higher. Since you list Windows Server 2016 there might be incompatibilities.



> Hi @laoyigrace, thanks for your inquiry and apologies for your inconvenience!
> 
> From what I can tell, Unity cannot load our binaries and/or respective dependencies. Can you follow the following steps:
> 
> 1. Make sure the files listed in the error messages actually exist.
> 2. Please read and follow the steps listed on this page: https://docs.microsoft.com/en-us/azure/remote-rendering/overview/system-requirements. In particular, make sure you have all required software listed under "Software" installed.
> 
> Also please be aware that we require Windows 10 version 1903 or higher. Since you list Windows Server 2016 there might be incompatibilities.

thank you, I see.
