### ISSUE TITLE
[Remote rendering problem] TransportPortBusy

### ISSUE THREAD

**Issue by WikkidEdd** [Azure/azure-remote-rendering#24]
**Describe the problem**

When running an ARR session one of the clients couldn't connect the running instance and showed the error TransportPortBusy. 
It tried on multiple times to connect and failed with the same error. Then after a short while restarting the app the client was able to connect to the still running instance.

The documentation on the error is quite limited. Is this something wrong with our app or is it a server-side issue that resolved itself after a short time?

**Comment by jumeder** [comment]
Hi @WikkidEdd, sorry to hear you are having trouble again. I can confirm this issue is not a fault in your app. This is a known service-side issue which we are currently actively working on fixing. For the moment, I'm afraid the only workarounds are either trying to reconnect until it works again or stopping the session and starting a new one.

I'll let you know as soon as we remedied the situation.

**Comment by ChristopherManthei** [comment]
Hi @WikkidEdd, we have just released [version 1.0.5](https://github.com/Azure/azure-remote-rendering/releases/tag/1.0.5) that should hopefully address the issue. From the release announcement:
1. Fixed an issue where a failed connection attempt would cause the server to take 20sec to timeout instead of the intended 5sec, resulting in TransportPortBusy response on further connect attempts until the 20sec timeout was hit.
2. Added improvements to reduce the likelyhood of a client failing to connect with result TransportPortBusy. The client should now receive TransportConnectionFailed in case the UDP transport connection failed.

The first change is a server only fix but for the second fix you will need to update your client SDK. If you hit the problem again (TransportConnectionFailed on connect attempt), please let us know. Note that there are various reasons why the connection to the server can fail so we suggest retrying on failure in the client application.

**Comment by tfb-azure** [comment]
I have been following the Quickstart tutorial for rendering models on Unity. I have downloaded the required version of Unity and Unity Hub. The Remote Rendering Account under Azure is showing that the session is Ready but Unity is giving "TransportPortBusy". I have uninstalled my Bitdefender Anti-virus and I am not connected to any VPN as well. 

Remote Rendering Domain: eastus2.mixedreality.azure.com
Account Domain: eastus.mixedreality.azure.com
VM size: Standard

What am I missing?

**Comment by onlyprince-debug** [comment]
I have been following the Quickstart tutorial for rendering models on Unity. I have downloaded the required version of Unity and Unity Hub. The Remote Rendering Account under Azure is showing that the session is Ready but Unity is giving "TransportPortBusy". I have uninstalled my Bitdefender Anti-virus and I am not connected to any VPN as well.

Remote Rendering Domain: eastus2.mixedreality.azure.com
Account Domain: eastus.mixedreality.azure.com
VM size: Standard

What am I missing?

**Comment by jumeder** [comment]
Hi @onlyprince-debug, sorry to hear that you are having problems and sorry for the delayed response. The screenshot you posted shows **HandshakeUnreachable** which indicates that you are having problems establishing the UDP transport.
As UDP is stateless we use a timeout of five seconds before a connection attempt is aborted and new connections are accepted by the server. During this time you may encounter **TransportPortBusy**. You will also encounter **TransportPortBusy** if you attempt to establish two or more connections to a single server (only one connection is allowed to exist at any given time).

First, make sure that your firewall allows TCP and UDP traffic [according to our documentation](https://docs.microsoft.com/en-us/azure/remote-rendering/overview/system-requirements#network-firewall). If that doesn't fix the problem, feel free to check back here again. I'll have a discussion with the team on possible debugging options in the meantime.

**Comment by jumeder** [comment]
I'll close this issue for now due to inactivity.
