### ISSUE TITLE
[Question] Are there any server side performance implications to enabling anti aliasing when running on windows desktop?

### ISSUE THREAD

**Issue by WikkidEdd** [Azure/azure-remote-rendering#26]
Our app runs both on HoloLens and Windows desktop and we make extensive use of ARR alongside locally rendered content. We have MSAA switched on of the locally rendered content when we're running on desktop, but we can see that upon connection to an ARR session the local content is no longer anti-aliased.

Digging into the code we can see that the proxy camera's render texture is created disregarding the global MSAA settings. If we modify the code to create the render texture with MSAA the local content renders as we like.

I know what the performance implications of turning antialiasing on for a standard desktop app are, but I wasn't sure whether enabling MSAA on the proxy texture would somehow setup an oversized render target on the server increasing both GPU and bandwidth overheads?

Are there any other considerations for enabling MSAA that we should be aware of?

**Comment by FlorianBorn71** [comment]
Hi and thanks for detailed elaboration. The server side MSAA setting is fully independent from the client setting. In fact the server always renders with MSAA enabled, but the video stream (color and depth buffer) does not hold per-sample information. That's why you get aliasing when the remote content is merged with local content.

I'll create a ticket on our end to fix this client MSAA setting as well. The problem might be more involved later in the pipeline (and maybe even break when running on HL where reprojection is performed?) but that's what we will be looking into as part of the ticket.

If your local fix works for you, there is at least nothing to worry about as far as server performance is concerned.

**Comment by WikkidEdd** [comment]
Great, thanks. I wouldn't expect or want it to run with MSAA on the HoloLens anyway.

**Comment by FlorianBorn71** [comment]
SDK 1.0.6 has been released on github and it has the proposed change in it.
