### ISSUE TITLE
[Remote rendering problem] Can't pass trough the ConnectToRuntime step on HoloLens 2, but it works on Unity

### ISSUE THREAD

**Issue by Cyhzault** [Azure/azure-remote-rendering#28]
**Describe the problem**

I'm using Azure Remote rendering for an industrial project i'm working on. I started with version 0.1.78 and followed the tutorial as described in the online documentation. I recently upgraded my project to the version 1.0.1  and incorporated some of the features from the Showroom app. The project is working perfectly fine on Unity Editor (2019.4.19f1), I successfuly managed to connect and interact with a custom remote model as Intented. 

The issue occurs only on HoloLens 2 after deploying both on ARM and ARM64 :
	1 - Application passes Identification step
	2 - Application launches or finds a remote session
	3 - When the session is ready, the application is failing to pass the ConnectToRuntime step.

The ConnectRuntimeToRemoteSession function is called : 
![image](https://user-images.githubusercontent.com/10668065/112543552-35234400-8db6-11eb-9ec6-446c0e62b45f.png)

Here is the function that receive the status update event : 

![image](https://user-images.githubusercontent.com/10668065/112542460-e0cb9480-8db4-11eb-82e7-db8339372032.png)

The logs are the following :
 - ConnectionStatus : CONNECTING | Runtime Connection status :  SUCCESS 
 - ConnectionStatus : CONNECTING | Runtime Connection status : SUCCESS 
 - ConnectionStatus : CONNECTING   | Runtime Connection status : SUCCESS 
 - ConnectionStatus : **DISCONNECT**   |  Runtime Connection status :  **FAIL**

As read on the documentation i'm keeping the ARRSessionService Updated in the LateUpdate()
![image](https://user-images.githubusercontent.com/10668065/112543491-22a90a80-8db6-11eb-9028-dbec2c5d940b.png)

I'm really surprised about this bug as i didn't encounter any issue on Unity and as it used to work on HoloLens before the upgrade. 

Any clues about what is causing the issue ?

Thanks for your help

**Comment by Cyhzault** [comment]
Hello there,

In the end, I managed to make it works by updating to version 1.0.4 and re-importing all my librairies. I also increased the delay between each of my requests attempts.

I don't really know what causes the failure in the first place and I'm still surprised about the difference of behaviour between HoloLens and Unity.

**Comment by ChristopherManthei** [comment]
Hi Cyhzault,

Glad to hear you could solve your problem. In general, you should only try to connect again once the previous attempt has failed. This can be observed by either the returned async task completing or the connection status changing back to disconnected.

The difference between Unity and HoloLens is mostly caused by Unity's cache.
We have had problems with Unity's cache being corrupted after upgrading packages, see [compile failures when compiling Unity samples](https://docs.microsoft.com/en-us/azure/remote-rendering/resources/troubleshoot#compile-failures-when-compiling-unity-samples-for-hololens-2). Normally this results in compile errors but the same steps should be taken if things suddenly stop working for any clear reason to rule out Unity's cache. So after each major upgrade, clear the project's cache folders as described in the link and build the project into an empty folder.

Cheers,
Christopher

**Comment by Cyhzault** [comment]
Hi Christopher,

Indeed, I'm waiting for the previous attempt to fails before trying again. You must be right, I think it was only a silent cache Issue, i will keep that in mind for the future upgrades.  

Thanks for your feedback. 
Problem solved, I'm closing the issue.

Regards,
Alexis.
