### ISSUE TITLE
[Question] ARM support with OpenXR and Unity

### ISSUE THREAD

**Issue by ujell** [Azure/azure-remote-rendering#42]
Is ARM platform supported with OpenXR in Unity? Currently, when I deploy to the device I get the following exception in `UnityEngine.SubsystemsModule.cpp`:

`Exception thrown at 0x76D4198E (ucrtbase.dll) in HoloIndustrieStadtpark.exe: 0xC0000005: Access violation reading location 0x00010000.`

Everything is up-to-date and same project with same settings works with ARM64 (and in Editor). Additionally, simply adding the Azure Remote Rendering package to a new project is enough to get this exception. 

The showcase app (which does not use OpenXR) works on both platforms. Am I missing a step or a setting? Tutorials recommend ARM64, but it's not explicitly stated as a prerequisites or requirement anywhere. This is relevant for us since MixedReality-WebRTC only works with ARM and we will select our tools according to this.

Thanks in advance!

**Comment by MalcolmTyrrell** [comment]
Hi. Thanks for your report. We've reproduced this issue locally, and we're looking into it.

**Comment by FlorianBorn71** [comment]
Hi!
We reached out to Unity with a repro and we got confirmation from them that this issue has been addressed for the upcoming OpenXR plugin (version 1.2.9 that is).
Would the cadence of a regular Unity minor version update be sufficient for you? Or are you blocked so that we should look into ways to provide you with a patch?

Best regards!
Florian

**Comment by ujell** [comment]
Hi, thank you for checking this out! 

Unity update is good enough; we are still on development phase so no need to spend your time on an already resolved issue.
