### ISSUE TITLE
[Question] Reading .arrAsset format

### ISSUE THREAD

**Issue by sidoverflow** [Azure/azure-remote-rendering#47]
I understand that .arrAsset is a proprietary binary format. Is there an SDK or some other way to read data from the .arrAsset file? (vertex information, etc.)

**Comment by jakrams** [comment]
There is no way to inspect the arrAsset format. We ensure that the service is able to load all arrAssets, no matter how old they are, but we reserve the option to change pretty much anything inside it, as the service and customer needs evolve. Since the format stores data optimized for ARR, there is really no use to looking inside it, you wouldn't be able to load it into any program (other than a HEX editor).
There is also nothing interesting to find in the format, it's really just your FBX/GLTF data converted to a more linear structure. All the ARR magic happens in the cloud ;-)
