### ISSUE TITLE
[Conversion Problem] Asset Conversion taking a long/variable amount of time

### ISSUE THREAD

**Issue by robbbbbb** [Azure/azure-remote-rendering#58]
**Describe the problem**

The asset conversion API seems to be running for unpredictable amounts of time, often taking a very long time, despite the input models being very simple.

We're wondering if this is some temporary instability or whether we're doing something fundamentally wrong with how we call the service.

**Provide additional information**

We raised this issue https://github.com/Azure/azure-remote-rendering/issues/56 last week regarding rendering performance with high object count. The suggestions to:

1. Switch to sceneGraph : static; and
2. Pay attention to the warnings in <file>.results.json and start using better file layout via the blobPrefix in the conversion input

led us to review the system we use to orchestrate our conversions. This in turn lead us to start looking more closely at how long some conversions were taking. Very long was the answer.

I've spent the morning comparing conversions posted to the API through our own system and conversions posted through the [Remote Rendering Asset Tool](https://github.com/Azure/azure-remote-rendering-asset-tool). In both cases I observed radically different and long conversion times with the same input model. In most cases the conversion takes several minutes even to go from NotStarted to Running, and then can be in the Running state for anything from < 1m to > 20m. 

Some conversion IDs:

From our system: 
f418d94f-1613-43d2-9d34-671279bb8704 (used sceneGraph: static, took 27m 38s)

From the ARRT:
DCDDB70D-2281-0346-85C3-466CA15D8E72 (used sceneGraph: dynamic, took 17m 24s)
E60A7515-DC31-3445-A34E-8F5F9AE96716 (used sceneGraph: static, took 6m 30s)

In all cases the inputs were this simple Duck model from the gltf samples repo https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/Duck/glTF-Binary/Duck.glb. And in all cases the input was put inside a virtual directory, provided in the blobPrefix argument to the conversion request.

**Comment by FlorianBorn71** [comment]
Thanks for the report. We are indeed seeing variation in conversion execution times recently and we are analyzing it. 

What I can say for sure is that this problem is independent of the actual conversion settings (e.g. "static" vs. "dynamic" scene graph). Instead, it's a variation in the actual VM provisioning time that is a constant overhead and does not scale with the complexity of the model.

I'll keep you updated...

**Comment by robbbbbb** [comment]
Hey @FlorianBorn71, any update on this? I'm still seeing very long conversion times this morning (>15m)

**Comment by FlorianBorn71** [comment]
Hi, we were able to mitigate one specific problem that might have caused queuing times that are longer than usual. This fix will go out with a release this week.
In general, we are always interested to keep the startup overhead low, so that startup times in the order of magnitude you were seeing are the exception. 
Feel free to ping us on this thread when this happens again after the release.
