### ISSUE TITLE
Some Failed conversions not producing result.json files in the output container

### ISSUE THREAD

**Issue by robbbbbb** [Azure/azure-remote-rendering#86]
**Describe the problem**

Some asset conversions which end in the Failed state didn't output <asset name>.result.json files in the output directory as expected https://learn.microsoft.com/en-us/azure/remote-rendering/how-tos/conversion/get-information

**Provide additional information**

This seems to have been confined to 3 conversions we performed between 26th September and 15th October this year. Conversion IDs below (assuming they still exist in your system):

27a607b0-5ded-43e6-8452-27f87917cb92
9581f286-3413-4027-9037-9c3cdf71fa23
509125b0-135c-4b2e-b822-a379f3e7867a

All conversions (both failed and successful) since then seem to have produced result.json files correctly, including one of these assets, so our guess is that there was a service problem during that period. It would be good to have that confirmed though, so we can cease any further investigation on our side.

**Comment by ChristopherManthei** [comment]
Hi @robbbbbb 
 
The **.result.json** file was not written out, because the step in the conversion, that writes this file was not reached for these conversions. The json only contains errors that occurred during the actual conversion process, so if anything fails beforehand the file will be missing. This could be for example a service outage as you mentioned or simply an authentication issue, so that the service couldn't download the source files from the input container. Of course, if there were issues with the output container, then no **result.json** can be written, because we can't write to the storage.

In cases without a **result.json** it is worthwhile to check the failure reason from the [Get Conversion - REST API](https://learn.microsoft.com/rest/api/mixedreality/2021-01-01/remote-rendering/get-conversion?tabs=HTTP). It should contain the information about service/authentication issues in the response body.

We will update the documentation to make this clearer.

Cheers,
Christopher

**Comment by robbbbbb** [comment]
Ah, thanks, falling back to the error information in the conversion status response is a useful workaround, thanks.
